export const integrationStates = {
  multiviewer: false,
  autoUpdater: false,
  f1tvLiveSession: false,
  homeAssistant: false,
  homebridge: false,
  philipsHue: false,
  govee: false,
  streamdeck: false,
  openrgb: false,
  mqtt: false,
  wled: false,
  tradfri: false,
  webserver: false,
};
