import { IConfig } from "./config_types";

export const defaultConfig: IConfig = {
  autoTurnOffLightsWhenSessionEnds: true,
  defaultBrightness: 100,
  goBackToStatic: true,
  goBackToStaticEnabledEvents: ["greenFlag"],
  goBackToStaticDelay: 10,
  staticBrightness: 70,
  hideLogs: true,
  startMultiViewerWhenAppStarts: false,
  eventColors: {
    static: {
      r: 255,
      g: 255,
      b: 255,
    },
    greenFlag: {
      r: 0,
      g: 255,
      b: 0,
    },
    yellowFlag: {
      r: 255,
      g: 150,
      b: 0,
    },
    redFlag: {
      r: 255,
      g: 0,
      b: 0,
    },
    safetyCar: {
      r: 255,
      g: 150,
      b: 0,
    },
    virtualSafetyCar: {
      r: 255,
      g: 150,
      b: 0,
    },
    virtualSafetyCarEnding: {
      r: 255,
      g: 150,
      b: 0,
    },
  },
  effects: [
    {
      id: 0,
      name: "Fastest Lap",
      trigger: "fastestLap",
      enabled: true,
      actions: [
        {
          type: "on",
          color: {
            r: 91,
            g: 0,
            b: 166,
          },
          brightness: 100,
        },
        {
          type: "delay",
          delay: 1000,
        },
        {
          type: "go_back_to_current_status",
        },
      ],
      amount: 1,
    },
  ],
  multiviewerLiveTimingURL: "http://localhost:10101",
  multiviewerCheck: true,
  philipsHueEnabled: false,
  philipsHueBridgeIP: undefined,
  philipsHueDeviceIDs: [],
  philipsHueEntertainmentZoneIDs: [],
  philipsHueToken: undefined,
  philipsHueThirdPartyCompatiblityMode: false,
  philipsHueEnableFade: false,
  philipsHueEnableFadeWithEffects: false,
  ikeaEnabled: false,
  ikeaSecurityCode: "",
  ikeaIdentity: undefined,
  ikeaPreSharedKey: undefined,
  ikeaDeviceIDs: [],
  goveeEnabled: false,
  openrgbEnabled: false,
  openrgbServerIp: "localhost",
  openrgbServerPort: 6742,
  homeAssistantEnabled: false,
  homeAssistantHost: "",
  homeAssistantPort: 8123,
  homeAssistantToken: "",
  homeAssistantDevices: [],
  wledEnabled: false,
  wledDevices: [],
  mqttEnabled: false,
  mqttHost: "",
  mqttPort: 1883,
  mqttUsername: "",
  mqttPassword: "",
  streamdeckEnabled: false,
  discordRPCEnabled: false,
  discordRPCAvoidSpoilers: true,
  webserverEnabled: false,
  webserverPort: 20202,
  debugMode: false,
  updateChannel: "latest",
  analytics: true,
};
