import { IConfig } from "./IConfig";

export const defaultConfig: IConfig = {
  autoTurnOffLightsWhenSessionEnds: true,
  defaultBrightness: 100,
  goBackToStatic: true,
  goBackToStaticEnabledFlags: ["green"],
  goBackToStaticDelay: 10,
  staticBrightness: 70,
  hideLogs: true,
  startMultiViewerWhenAppStarts: false,
  colorSettings: {
    staticColor: {
      r: 255,
      g: 255,
      b: 255,
    },
    green: {
      r: 0,
      g: 255,
      b: 0,
    },
    yellow: {
      r: 255,
      g: 150,
      b: 0,
    },
    red: {
      r: 255,
      g: 0,
      b: 0,
    },
    safetyCar: {
      r: 255,
      g: 150,
      b: 0,
    },
    vsc: {
      r: 255,
      g: 150,
      b: 0,
    },
    vscEnding: {
      r: 255,
      g: 150,
      b: 0,
    },
  },
  effectSettings: [
    {
      name: "Fastest Lap",
      id: 0,
      trigger: "fastestLap",
      enabled: true,
      actions: [
        {
          type: "on",
          color: {
            r: 91,
            g: 0,
            b: 166,
          },
          brightness: 100,
        },
        {
          type: "delay",
          delay: 1000,
        },
        {
          type: "go_back_to_current_status",
        },
      ],
      amount: 1,
    },
  ],
  multiviewerLiveTimingURL: "http://localhost:10101",
  multiviewerCheck: true,
  philipsHueEnabled: false,
  philipsHueBridgeIP: undefined,
  philipsHueDeviceIDs: [],
  philipsHueEntertainmentZoneIDs: [],
  philipsHueToken: undefined,
  philipsHue3rdPartyCompatiblityMode: false,
  philipsHueEnableFade: false,
  philipsHueEnableFadeWithEffects: false,
  ikeaEnabled: false,
  ikeaSecurityCode: "",
  ikeaIdentity: undefined,
  ikeaPreSharedKey: undefined,
  ikeaDeviceIDs: [],
  goveeEnabled: false,
  openRGBEnabled: false,
  openRGBServerIP: "localhost",
  openRGBServerPort: 6742,
  homeAssistantEnabled: false,
  homeAssistantHost: "",
  homeAssistantPort: 8123,
  homeAssistantToken: "",
  homeAssistantDevices: [],
  wledEnabled: false,
  wledDevices: [],
  mqttEnabled: false,
  mqttHost: "",
  mqttPort: 1883,
  mqttUsername: "",
  mqttPassword: "",
  streamDeckEnabled: false,
  discordRPCEnabled: false,
  discordRPCAvoidSpoilers: true,
  webServerEnabled: false,
  webServerPort: 20202,
  debugMode: false,
  updateChannel: "latest",
  analytics: true,
  version: "3.0.0",
};
